name: Check for changes

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git fetch all
        run: git fetch --all

      - name: Check for changes in /apps
        id: check_apps
        run: |
          if git diff --name-only origin/main | grep '^apps/[^/]\+/'; then
            echo "Apps changed"
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "No changes in apps"
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Check for changes in /.changeset
        id: check_changeset
        if: env.changed == 'true'
        run: |
          if git diff --name-only origin/main | grep '^.changeset/'; then
            echo "Changeset updated"
            echo "changeset_present=true" >> $GITHUB_ENV
          else
            echo "No changeset found"
            echo "changeset_present=false" >> $GITHUB_ENV
          fi

      - name: Post Warning if Changeset is Missing
        if: env.changed == 'true' && env.changeset_present == 'false'
        run: |
          COMMENT_BODY="⚠️ **Warning:** Changes detected in \`/apps\` subdirectories, but no changeset file was found in \`./changeset\`. Please add a changeset file by running \`pnpm changeset\`."
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments \
               -d "{\"body\": \"$COMMENT_BODY\"}"
          exit 1